# Generated by Django 6.0.2 on 2026-05-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='asunto',
            field=models.CharField(default='prueba', max_length=50),
            preserve_default=False,
        ),
    ]
