# Generated by Django 6.0.2 on 2026-06-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_incidencias_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
