# Generated by Django 6.0.2 on 2026-06-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_incidencias_resuelto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencias',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'ordering': ['-fecha_creacion']},
        ),
    ]
