# Generated by Django 6.0.2 on 2026-06-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0004_alter_incidencias_options_alter_respuesta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencias',
            name='prioridad',
            field=models.CharField(default='baja', max_length=10),
        ),
    ]
