# Generated by Django 6.0.2 on 2026-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='state',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('completed', 'Completada')], default='pending', max_length=20),
        ),
    ]
