# Generated by Django 6.0.2 on 2026-05-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.CharField(default='employee', max_length=50),
            preserve_default=False,
        ),
    ]
