# Generated by Django 6.0.2 on 2026-05-27 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_tarea_state'),
        ('usuarios', '0004_usuario_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='departamentos.departamento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(default='employee', max_length=50),
        ),
    ]
