# Generated by Django 6.0.2 on 2026-05-27 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuario_departamento_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(default='manager', max_length=50),
        ),
    ]
