# Generated by Django 6.0.2 on 2026-06-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='perfil/'),
        ),
    ]
